package com.grocery.dao;

import com.grocery.domain.AdminMenu;

import java.util.List;

public interface AdminMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_MENU
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_MENU
     *
     * @mbggenerated
     */
    int insert(AdminMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_MENU
     *
     * @mbggenerated
     */
    int insertSelective(AdminMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_MENU
     *
     * @mbggenerated
     */
    AdminMenu selectByPrimaryKey(Integer id);

    List<AdminMenu> selectAdminMenuOrder();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_MENU
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AdminMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_MENU
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdminMenu record);
}