package com.grocery.dao;

import com.grocery.domain.ArticleSharing;

import java.util.List;

public interface ArticleSharingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARTICLE_SHARING
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARTICLE_SHARING
     *
     * @mbggenerated
     */
    int insert(ArticleSharing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARTICLE_SHARING
     *
     * @mbggenerated
     */
    int insertSelective(ArticleSharing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARTICLE_SHARING
     *
     * @mbggenerated
     */
    ArticleSharing selectByPrimaryKey(Integer id);

    List<ArticleSharing> selectWithoutDetailByPaging(Integer pageIndex, Integer pageSize);

    Integer getCount();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARTICLE_SHARING
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ArticleSharing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARTICLE_SHARING
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ArticleSharing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARTICLE_SHARING
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ArticleSharing record);
}