package com.grocery.dao;

import com.grocery.domain.Avator;
import org.springframework.stereotype.Repository;

@Repository
public interface AvatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVATOR
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVATOR
     *
     * @mbggenerated
     */
    int insert(Avator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVATOR
     *
     * @mbggenerated
     */
    int insertSelective(Avator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVATOR
     *
     * @mbggenerated
     */
    Avator selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVATOR
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Avator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVATOR
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Avator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVATOR
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Avator record);
}