package com.grocery.dao;

import com.grocery.domain.ClientInfo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ClientInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLIENT_INFO
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLIENT_INFO
     *
     * @mbg.generated
     */
    int insert(ClientInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLIENT_INFO
     *
     * @mbg.generated
     */
    int insertSelective(ClientInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLIENT_INFO
     *
     * @mbg.generated
     */
    ClientInfo selectByPrimaryKey(Integer id);

    ClientInfo selectByIp(@Param("ip") String ip);

    List<ClientInfo> selectClientInfoByPaging(Integer pageIndex, Integer pageSize);

    Integer getCount();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLIENT_INFO
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ClientInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLIENT_INFO
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ClientInfo record);
}