package com.grocery.dao;

import com.grocery.domain.InstationSenderContent;
import org.springframework.stereotype.Repository;

@Repository
public interface InstationSenderContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTATION_SENDER_CONTENT
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTATION_SENDER_CONTENT
     *
     * @mbg.generated
     */
    int insert(InstationSenderContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTATION_SENDER_CONTENT
     *
     * @mbg.generated
     */
    int insertSelective(InstationSenderContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTATION_SENDER_CONTENT
     *
     * @mbg.generated
     */
    InstationSenderContent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTATION_SENDER_CONTENT
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InstationSenderContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTATION_SENDER_CONTENT
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InstationSenderContent record);
}