package com.grocery.dao;

import com.grocery.domain.MessageBoardSubreply;

import java.util.List;

public interface MessageBoardSubreplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESSAGE_BOARD_SUBREPLY
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESSAGE_BOARD_SUBREPLY
     *
     * @mbggenerated
     */
    int insert(MessageBoardSubreply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESSAGE_BOARD_SUBREPLY
     *
     * @mbggenerated
     */
    int insertSelective(MessageBoardSubreply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESSAGE_BOARD_SUBREPLY
     *
     * @mbggenerated
     */
    MessageBoardSubreply selectByPrimaryKey(Integer id);

    List<MessageBoardSubreply> selectpaging(Integer pageIndex, Integer pageSize,String id);

    Integer getCountByMessageBoardId(String id);

    Integer getCount(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESSAGE_BOARD_SUBREPLY
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MessageBoardSubreply record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESSAGE_BOARD_SUBREPLY
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MessageBoardSubreply record);
}