package com.grocery.dao;

import com.grocery.domain.NavigatationMenu;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface NavigatationMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAVIGATATION_MENU
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAVIGATATION_MENU
     *
     * @mbggenerated
     */
    int insert(NavigatationMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAVIGATATION_MENU
     *
     * @mbggenerated
     */
    int insertSelective(NavigatationMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAVIGATATION_MENU
     *
     * @mbggenerated
     */
    NavigatationMenu selectByPrimaryKey(Integer id);

    List<NavigatationMenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAVIGATATION_MENU
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NavigatationMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAVIGATATION_MENU
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NavigatationMenu record);
}