package com.grocery.dao;

import com.grocery.domain.NewsSharing;

public interface NewsSharingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS_SHARING
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS_SHARING
     *
     * @mbggenerated
     */
    int insert(NewsSharing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS_SHARING
     *
     * @mbggenerated
     */
    int insertSelective(NewsSharing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS_SHARING
     *
     * @mbggenerated
     */
    NewsSharing selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS_SHARING
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NewsSharing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS_SHARING
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(NewsSharing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS_SHARING
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NewsSharing record);
}