package com.grocery.dao;

import com.grocery.domain.PersonalInfo;

public interface PersonalInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSONAL_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSONAL_INFO
     *
     * @mbggenerated
     */
    int insert(PersonalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSONAL_INFO
     *
     * @mbggenerated
     */
    int insertSelective(PersonalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSONAL_INFO
     *
     * @mbggenerated
     */
    PersonalInfo selectByPrimaryKey(Integer id);

    PersonalInfo selectByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSONAL_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PersonalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSONAL_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PersonalInfo record);
}