package com.grocery.dao;

import com.grocery.domain.PersonalMenu;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PersonalMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSONAL_MENU
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSONAL_MENU
     *
     * @mbggenerated
     */
    int insert(PersonalMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSONAL_MENU
     *
     * @mbggenerated
     */
    int insertSelective(PersonalMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSONAL_MENU
     *
     * @mbggenerated
     */
    PersonalMenu selectByPrimaryKey(Integer id);

    List<PersonalMenu> selectPersonalMenuOrder();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSONAL_MENU
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PersonalMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSONAL_MENU
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PersonalMenu record);
}