package com.grocery.dao;

import com.grocery.domain.PhotographyPhoto;
import org.springframework.stereotype.Repository;

@Repository
public interface PhotographyPhotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHOTOGRAPHY_PHOTO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHOTOGRAPHY_PHOTO
     *
     * @mbggenerated
     */
    int insert(PhotographyPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHOTOGRAPHY_PHOTO
     *
     * @mbggenerated
     */
    int insertSelective(PhotographyPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHOTOGRAPHY_PHOTO
     *
     * @mbggenerated
     */
    PhotographyPhoto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHOTOGRAPHY_PHOTO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PhotographyPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHOTOGRAPHY_PHOTO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(PhotographyPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHOTOGRAPHY_PHOTO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PhotographyPhoto record);
}