package com.grocery.dao;

import com.grocery.domain.SoftwareSharing;

public interface SoftwareSharingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOFTWARE_SHARING
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOFTWARE_SHARING
     *
     * @mbggenerated
     */
    int insert(SoftwareSharing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOFTWARE_SHARING
     *
     * @mbggenerated
     */
    int insertSelective(SoftwareSharing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOFTWARE_SHARING
     *
     * @mbggenerated
     */
    SoftwareSharing selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOFTWARE_SHARING
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SoftwareSharing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOFTWARE_SHARING
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SoftwareSharing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOFTWARE_SHARING
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SoftwareSharing record);
}